/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package templatejava;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {

	private static Logger log = LogManager.getLogger(App.class);


    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

		log.info("Testing log info");
		log.debug("Testing log debug");
    }
}
