/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package templatejava;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.Test;

public class AppTest {

	private static Logger log = LogManager.getLogger(AppTest.class);

    @Test
   	public void appHasAGreeting() {
		log.info("Testing log info");
		log.debug("Testing log debug");

		assertEquals(5, 5, "Testing Equals");

    }

	@Test
   	public void appHasTest() {
        App classUnderTest = new App();
		assertEquals( classUnderTest.getGreeting(), "Hello World!", "Not Fail");
	}
}
